### ISSUE TITLE
LilyJSSVGCompileHelper.py only Python2 compatible

### ISSUE THREAD

**Issue by mtarenskeen** [paolo-prete/LilyJSSVG#1]
LilyJSSVGCompileHelper.py is not compatible with Python3 (yet). 

Easy to fix, to make it work with Python2 and Python3:
- Change `print` statements to `print()` functions 

-- `ctype, pdict = cgi.parse_header(self.headers.getheader('content-type'))`
++ `ctype, pdict = cgi.parse_header(self.headers.get('content-type'))`

After these easy fixes it still gives me some errors:
Something with f.write() has to be fixed but I have not found the solution yet. (Something with the way python3 handles bytes and strings? )

**Comment by paolo-prete** [comment]
Thanks for your feedback. Now it should have been fixed. Please test it, so I close the issue.

**Comment by mtarenskeen** [comment]
Tested with Python 2.7.17 and 3.7.5 and Firefox on Linux Fedora 31. Seems to be working in both Python versions now. Thanks.

**Comment by paolo-prete** [comment]
It has been ported to 3.x. I don't know why it (apparently) works on 2.7.17 (it doesn't work on 2.7.15, though). Anyway, I can close the issue. Thanks.
